name: 05 - 1 - Filters Activity and Activity Types

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  filter-activity-types:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a PR is closed AND base branch is main"