name: 17 - 1 - Custom Actions - Composite
run-name: 17 - 1 - Custom Actions - Composite | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: choice
        default: 'dev'
        description: 'Which enviroment to target for dependecy installation'
        options:
          - dev
          - prod
env:
    working-directory: 17-custom-actions/react-app
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node and NPM dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: 20.x
          working-directory: ${{ env.working-directory }}
          target-env: ${{ inputs.target-env }}
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
